### ISSUE TITLE
BUG | 压缩算法导致MCSL2无法安装此插件的压缩包

### ISSUE THREAD

**Issue by StarryCamile** [MCSLTeam/Server_Properties_Editor#1]
直接使用release的zip安装插件无法安装，我给你解压后重新用BandiZIP打包就可以安装了，话说你用的什么软件

**Comment by lxhtt** [comment]
Bandizip。我觉得有可能是压缩算法导致的。

**Comment by lxhtt** [comment]
我使用的是XZ压缩算法。应该就是因为这个。换成Deflate算法就ok了。已重新上传Release。
